--Sample Vendor data

insert into vendor (id, emailId, name, registrationDate) values (1, 'balexander0@imdb.com', 'Browseblab', '2016-06-21');
insert into vendor (id, emailId, name, registrationDate) values (2, 'bpowell1@blinklist.com', 'Kare', '2016-06-05');
insert into vendor (id, emailId, name, registrationDate) values (3, 'wwalker2@goo.ne.jp', 'Innotype', '2016-06-27');
insert into vendor (id, emailId, name, registrationDate) values (4, 'vferguson3@naver.com', 'Kaymbo', '2016-05-22');
insert into vendor (id, emailId, name, registrationDate) values (5, 'djordan4@ovh.net', 'Chatterpoint', '2016-04-22');
insert into vendor (id, emailId, name, registrationDate) values (6, 'jweaver5@bizjournals.com', 'Realbridge', '2016-05-27');
insert into vendor (id, emailId, name, registrationDate) values (7, 'esnyder6@netscape.com', 'Brightbean', '2016-04-16');
insert into vendor (id, emailId, name, registrationDate) values (8, 'rwatson7@about.me', 'Meedoo', '2016-04-08');
insert into vendor (id, emailId, name, registrationDate) values (9, 'svasquez8@fotki.com', 'Skinder', '2016-05-13');
insert into vendor (id, emailId, name, registrationDate) values (10, 'lharris9@stanford.edu', 'Edgeblab', '2016-05-22');


--Sample Customer data

insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (1, 'Todd', 'Harvey', 'tharvey0@japanpost.jp', '0', '9', '7090151810');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (2, 'Carl', 'Richardson', 'crichardson1@hc360.com', '0', '8', '9055790960');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (3, 'Martha', 'Fox', 'mfox2@statcounter.com', '1', '10', '9905593725');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (4, 'Brenda', 'Taylor', 'btaylor3@jigsy.com', '0', '10', '8917113873');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (5, 'Johnny', 'Burton', 'jburton4@cisco.com', '1', '10', '8641993031');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (6, 'Beverly', 'Dixon', 'bdixon5@nyu.edu', '0', '10', '9282939398');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (7, 'Lois', 'Jacobs', 'ljacobs6@go.com', '1', '3', '7132328588');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (8, 'Gloria', 'Daniels', 'gdaniels7@google.cn', '0', '10', '7059434980');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (9, 'Arthur', 'Walker', 'awalker8@fc2.com', '0', '7', '8902247848');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (10, 'Joseph', 'Palmer', 'jpalmer9@theglobeandmail.com', '1', '10', '9888015652');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (11, 'Maria', 'Kelley', 'mkelleya@zdnet.com', '0', '10', '8253963594');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (12, 'Christina', 'Murphy', 'cmurphyb@homestead.com', '0', '10', '7815608339');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (13, 'Julia', 'Jones', 'jjonesc@shop-pro.jp', '1', '9', '7378598927');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (14, 'Ryan', 'Bradley', 'rbradleyd@vistaprint.com', '0', '10', '7988064972');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (15, 'Ernest', 'Arnold', 'earnolde@ft.com', '1', '10', '7525747084');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (16, 'Brandon', 'Cook', 'bcookf@zdnet.com', '1', '10', '9900555733');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (17, 'Tammy', 'Cox', 'tcoxg@pen.io', '1', '10', '7476935861');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (18, 'Jimmy', 'Moore', 'jmooreh@kickstarter.com', '1', '9', '9457823773');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (19, 'Pamela', 'Powell', 'ppowelli@tamu.edu', '1', '9', '9586085652');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (20, 'Virginia', 'Elliott', 'velliottj@hostgator.com', '0', '6', '9533253603');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (21, 'Juan', 'Burton', 'jburtonk@sakura.ne.jp', '0', '10', '7736852415');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (22, 'Billy', 'Ray', 'brayl@nbcnews.com', '1', '6', '8258665041');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (23, 'Robin', 'Ward', 'rwardm@google.de', '0', '10', '9808848105');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (24, 'Jonathan', 'Woods', 'jwoodsn@odnoklassniki.ru', '1', '9', '9018085839');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (25, 'Kenneth', 'Porter', 'kportero@hud.gov', '1', '10', '9893410121');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (26, 'Susan', 'Sanchez', 'ssanchezp@wikipedia.org', '0', '10', '8787704595');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (27, 'John', 'Ferguson', 'jfergusonq@sitemeter.com', '0', '9', '8050902730');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (28, 'Sharon', 'Lane', 'slaner@over-blog.com', '1', '10', '9500751237');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (29, 'Russell', 'Butler', 'rbutlers@harvard.edu', '1', '10', '9812261772');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (30, 'Benjamin', 'Sims', 'bsimst@webs.com', '1', '10', '9698480238');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (31, 'Christopher', 'Boyd', 'cboydu@dropbox.com', '0', '8', '9775059718');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (32, 'Michael', 'Thomas', 'mthomasv@blog.com', '0', '10', '7632048848');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (33, 'Julia', 'Woods', 'jwoodsw@behance.net', '0', '7', '8502193399');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (34, 'Virginia', 'Morrison', 'vmorrisonx@dedecms.com', '1', '8', '9428750144');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (35, 'Steven', 'Jacobs', 'sjacobsy@ifeng.com', '0', '10', '8268742057');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (36, 'Brandon', 'Bowman', 'bbowmanz@mozilla.com', '0', '10', '9135733331');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (37, 'Virginia', 'Alexander', 'valexander10@blogger.com', '0', '9', '9649680639');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (38, 'Aaron', 'Butler', 'abutler11@oaic.gov.au', '1', '8', '9161494802');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (39, 'Karen', 'Torres', 'ktorres12@arizona.edu', '0', '10', '9039712611');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (40, 'Nicholas', 'Harvey', 'nharvey13@gmpg.org', '0', '9', '9314758696');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (41, 'Ruby', 'Morris', 'rmorris14@nhs.uk', '1', '7', '8120766423');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (42, 'Carolyn', 'Olson', 'colson15@moonfruit.com', '1', '7', '7285537230');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (43, 'Nicholas', 'Larson', 'nlarson16@bravesites.com', '1', '9', '8180792092');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (44, 'Christina', 'Austin', 'caustin17@eepurl.com', '1', '10', '9275392513');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (45, 'Lawrence', 'Sullivan', 'lsullivan18@ihg.com', '0', '9', '9868092530');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (46, 'Sandra', 'Alvarez', 'salvarez19@bigcartel.com', '1', '6', '8544400990');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (47, 'Carol', 'Freeman', 'cfreeman1a@purevolume.com', '1', '10', '8344839260');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (48, 'Shirley', 'Pierce', 'spierce1b@lycos.com', '1', '9', '9137691216');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (49, 'Emily', 'Harris', 'eharris1c@google.com.hk', '0', '10', '9988994498');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (50, 'Katherine', 'Bryant', 'kbryant1d@mail.ru', '1', '8', '7829925383');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (51, 'Willie', 'Richards', 'wrichards1e@webs.com', '1', '10', '8340483069');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (52, 'Randy', 'Dixon', 'rdixon1f@t-online.de', '1', '10', '8173347501');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (53, 'Walter', 'Lawson', 'wlawson1g@lulu.com', '1', '10', '9919703941');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (54, 'Harold', 'Olson', 'holson1h@tuttocitta.it', '0', '8', '9650205276');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (55, 'Jimmy', 'King', 'jking1i@t-online.de', '1', '8', '9041330266');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (56, 'Michael', 'Hawkins', 'mhawkins1j@phoca.cz', '1', '10', '9889240813');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (57, 'Diane', 'Wells', 'dwells1k@goodreads.com', '0', '10', '8479805380');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (58, 'Thomas', 'Nelson', 'tnelson1l@ed.gov', '0', '4', '8754571734');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (59, 'Jean', 'Alexander', 'jalexander1m@cdc.gov', '0', '10', '9370847748');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (60, 'Sean', 'Knight', 'sknight1n@house.gov', '1', '10', '7211934922');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (61, 'Jack', 'Bishop', 'jbishop1o@so-net.ne.jp', '0', '5', '9196124494');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (62, 'Carl', 'Rose', 'crose1p@europa.eu', '1', '8', '9552934665');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (63, 'Jessica', 'Mcdonald', 'jmcdonald1q@webeden.co.uk', '0', '10', '9572333011');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (64, 'Mildred', 'Parker', 'mparker1r@dagondesign.com', '0', '10', '7712712925');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (65, 'Debra', 'Carter', 'dcarter1s@senate.gov', '1', '9', '7217380131');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (66, 'Sara', 'Watkins', 'swatkins1t@livejournal.com', '0', '9', '9578748275');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (67, 'Douglas', 'Woods', 'dwoods1u@booking.com', '0', '9', '8028043955');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (68, 'Janet', 'Graham', 'jgraham1v@redcross.org', '0', '8', '7284307755');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (69, 'Matthew', 'Sanchez', 'msanchez1w@statcounter.com', '1', '10', '8076188832');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (70, 'Maria', 'Rose', 'mrose1x@stanford.edu', '0', '10', '8774988048');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (71, 'Samuel', 'Gilbert', 'sgilbert1y@mapquest.com', '0', '9', '9546776132');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (72, 'Phillip', 'Peters', 'ppeters1z@artisteer.com', '1', '8', '7441066054');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (73, 'Gregory', 'Burns', 'gburns20@etsy.com', '0', '10', '9005397125');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (74, 'Frank', 'Dunn', 'fdunn21@ovh.net', '0', '6', '8147314795');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (75, 'Amy', 'Roberts', 'aroberts22@dailymail.co.uk', '1', '10', '7445529056');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (76, 'Robin', 'Harvey', 'rharvey23@purevolume.com', '0', '10', '8789149531');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (77, 'Nicholas', 'Black', 'nblack24@discuz.net', '0', '9', '9229211234');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (78, 'Russell', 'Cole', 'rcole25@simplemachines.org', '0', '10', '9847097101');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (79, 'Matthew', 'Murray', 'mmurray26@zimbio.com', '0', '10', '8016969240');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (80, 'Edward', 'Hall', 'ehall27@army.mil', '1', '9', '9216139436');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (81, 'Marilyn', 'Edwards', 'medwards28@nba.com', '0', '10', '8932048273');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (82, 'Theresa', 'Walker', 'twalker29@youtube.com', '1', '6', '7749545248');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (83, 'Keith', 'Kelly', 'kkelly2a@cbc.ca', '0', '10', '9349262532');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (84, 'Helen', 'Hicks', 'hhicks2b@prlog.org', '0', '9', '8406896863');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (85, 'Judith', 'Rodriguez', 'jrodriguez2c@twitpic.com', '0', '9', '8753774937');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (86, 'Roy', 'Sanders', 'rsanders2d@go.com', '0', '10', '8000714495');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (87, 'Billy', 'Wilson', 'bwilson2e@vk.com', '1', '10', '8068499570');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (88, 'Michelle', 'Perry', 'mperry2f@icq.com', '1', '10', '9821524884');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (89, 'Roger', 'Hanson', 'rhanson2g@1688.com', '0', '8', '8125282540');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (90, 'Douglas', 'Diaz', 'ddiaz2h@weather.com', '1', '9', '7903305164');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (91, 'Benjamin', 'Ryan', 'bryan2i@over-blog.com', '1', '7', '7277769223');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (92, 'Jacqueline', 'Spencer', 'jspencer2j@blogtalkradio.com', '1', '9', '9827450762');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (93, 'Marilyn', 'Gibson', 'mgibson2k@vimeo.com', '0', '10', '9610583046');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (94, 'George', 'Reyes', 'greyes2l@sun.com', '1', '10', '9237545676');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (95, 'Catherine', 'Bell', 'cbell2m@instagram.com', '1', '10', '8357841479');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (96, 'Russell', 'Parker', 'rparker2n@behance.net', '1', '10', '7423511702');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (97, 'Brandon', 'Matthews', 'bmatthews2o@parallels.com', '0', '10', '7434402444');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (98, 'Jean', 'Jacobs', 'jjacobs2p@go.com', '0', '10', '9477714070');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (99, 'Raymond', 'Murphy', 'rmurphy2q@oaic.gov.au', '1', '10', '9414906806');
insert into Customer (id, firstName, lastName, emailId, gender, vendorID, mobileNo) values (100, 'Lisa', 'Alvarez', 'lalvarez2r@unblog.fr', '0', '10', '8008438224');